{"8":[6,12,6,19],"9":[1,16,1,23],"10":[10,9,10,35],"16":[10,9,10,35],"17":[1,24,1,48],"25":[1,16,1,49],"33":[1,16,1,49],"41":[1,16,1,49],"49":[4,1,4,7],"57":[6,12,6,19],"65":[6,22,6,24],"73":[6,25,6,33],"81":[6,34,6,39],"89":[6,25,6,40],"97":[6,41,6,42],"105":[6,25,6,43],"113":[6,45,6,50],"121":[6,51,6,52],"129":[6,45,6,53],"137":[6,22,6,54],"145":[6,57,6,59],"153":[6,60,6,65],"161":[6,57,6,66],"169":[6,12,6,66],"177":[6,5,6,67],"185":[9,24,9,32],"193":[9,33,9,41],"201":[9,24,9,42],"209":[9,24,9,42],"217":[9,24,9,42],"225":[10,9,10,21],"233":[10,26,10,35],"241":[10,37,10,45],"249":[10,46,10,58],"257":[10,64,10,72],"265":[10,46,10,73],"267":[10,46,10,63],"273":[10,37,10,74],"281":[10,37,10,75],"289":[11,11,11,16],"297":[11,11,11,16],"305":[11,5,11,17],"313":[8,5,12,4],"321":[4,18,13,2],"329":[4,18,13,2],"337":[4,18,13,2],"345":[4,18,13,2],"353":[4,18,13,2],"361":[4,18,13,2],"369":[4,18,13,2],"377":[4,18,13,2],"385":[4,1,13,2],"393":[4,1,13,3],"401":[1,1,13,3],"409":[1,1,13,3],"417":[6,12,6,66],"425":[10,5,10,75],"433":[4,18,13,2],"441":[4,18,13,2],"449":[1,1,13,3],"457":[1,1,13,3],"nBranches":4,"originalCodeFileName":"/home/james/nodejs/HiPar/node_modules/core-js/internals/call-with-safe-iteration-closing.js","instrumentedCodeFileName":"/home/james/nodejs/HiPar/node_modules/core-js/internals/call-with-safe-iteration-closing_jalangi_.js","code":"var anObject = require('../internals/an-object');\n\n// call something on iterator step with safe closing on error\nmodule.exports = function (iterator, fn, value, ENTRIES) {\n  try {\n    return ENTRIES ? fn(anObject(value)[0], value[1]) : fn(value);\n  // 7.4.6 IteratorClose(iterator, completion)\n  } catch (error) {\n    var returnMethod = iterator['return'];\n    if (returnMethod !== undefined) anObject(returnMethod.call(iterator));\n    throw error;\n  }\n};\n"}